# -*- coding: utf-8 -*-
"""
Created on Thu Jun  4 20:18:26 2020

@author: Samir
"""

CONTRACTION_MAP = {
  "ain't": "am not",
  "aren't": "are not",
  "can't've": "cannot have",
  "can't": "cannot",  
  "'cause": " because",
  "couldn't've": "could not have",
  "could've": "could have",  
  "couldn't": "could not",  
  "didn't": "did not",
  "didnt": "did not", 
  "doesn't": "does not",
  "doesnt": "does not",
  "don't": "do not",
  "dont": "do not",
  "hadn't've": "had not have",
  "hadn't": "had not",  
  "hasn't": "has not",
  "haven't": "have not",
  "he'd've": "he would have",
  "he'd": "he would", 
  "he'll've": "he will have",
  "he'll": "he will",
  "he's": "he is",
  "how'd'y": "how do you",
  "how'd": "how did",  
  "how'll": "how will",
  "how's": "how is",
  "I'd've": "I would have",
  "I'd": "I would",
  "I'll've": "I will have",
  "I'll": "I will",  
  "I'm": "I am",
  "I've": "I have",
  "i'd've": "I would have",
  "i'd": "I would",
  "i'll've": "I will have",
  "i'll": "I will",  
  "i'm": "I am",
  "i've": "I have",
  "isn't": "is not",
  "it'd've": "it would have",
  "it'd": "it would",
  "it'll've": "it will have",
  "it'll": "it will",  
  "it's": "it is",
  "let's": "let us",
  "Let's": "Let us",
  "ma'am": "madam",
  "mayn't": "may not",
  "mightn't've": "might not have",
  "might've": "might have",
  "mightn't": "might not",
  "mustn't've": "must not have",
  "must've": "must have",
  "mustn't": "must not",
  "needn't've": "need not have",
  "needn't": "need not",  
  "o'clock": "of the clock",
  "oughtn't've": "ought not have",
  "oughtn't": "ought not",
  "shan't've": "shall not have",
  "sha'n't": "shall not",
  "shan't": "shall not",
  "she'd've": "she would have",
  "she'd": "she would",
  "she'll've": "she will have",
  "she'll": "she will",  
  "she's": "she is",
  "shouldn't've": "should not have",
  "should've": "should have",
  "shouldn't": "should not",  
  "so've": "so have",
  "so's": "so is",
  "that'd've": "that would have",
  "that'd": "that would",  
  "that's": "that is",
  "there'd've": "there would have",
  "there'd": "there would",  
  "there's": "there is",
  "they'd've": "they would have",
  "they'd": "they would",
  "they'll've": "they will have",
  "they'll": "they will",  
  "they're": "they are",
  "they've": "they have",
  "to've": "to have",
  "wasn't": "was not",
  "we'd've": "we would have",
  "we'd": "we would", 
  "we'll've": "we will have",
  "we'll": "we will",  
  "we're": "we are",
  "we've": "we have",
  "weren't": "were not",
  "what'll've": "what will have",
  "what'll": "what will",  
  "what're": "what are",
  "what's": "what is",
  "what've": "what have",
  "when's": "when is",
  "when've": "when have",
  "where'd": "where did",
  "where's": "where is",
  "where've": "where have",
  "who'll've": "who will have",
  "who'll": "who will",  
  "who's": "who is",
  "who've": "who have",
  "why's": "why is",
  "why've": "why have",
  "will've": "will have",
  "won't": "will not",
  "won't've": "will not have",
  "wouldn't've": "would not have",
  "would've": "would have",
  "wouldn't": "would not",  
  "y'all'd've": "you all would have",
  "y'all'd": "you all would",  
  "y'all're": "you all are",
  "y'all've": "you all have",
  "y'all": "you all",
  "y'alls": "you alls",  
  "you'd've": "you would have",
  "you'd": "you would",  
  "you'll've": "you will have",
  "you'll": "you will",  
  "you're": "you are",
  "you've": "you have"
}